LastROMFolder = "/home/deck/ArcadeDeck/users/games/NDS/The Legend of Zelda: Phantom Hourglass"
LastBIOSFolder = ""
FastForwardFPS = 1000.0
PauseLostFocus = false
UITheme = ""
RecentROM = ["/home/deck/ArcadeDeck/users/games/NDS/Grand Theft Auto: Chinatown Wars/GTA Chinatown Wars.nds", "/home/deck/ArcadeDeck/users/games/NDS/The Legend of Zelda: Phantom Hourglass/The Legend of Zelda - Phantom Hourglass [U] [T+Rus_zelda64rus_v1.2].nds"]
AudioSync = false
TargetFPS = 60.0
LimitFPS = true
SlowmoFPS = 30.0

[Mic]
InputType = 1
Device = ""
WavPath = ""

[Audio]
Interpolation = 0
BitDepth = 0

[Instance0]
CheatFilePath = ""
EnableCheats = false
SaveFilePath = ""
JoystickID = 0
SavestatePath = ""

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM7]
Port = 3334
BreakOnStartup = false

[Instance0.Gdb.ARM9]
Port = 3333
BreakOnStartup = false

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.RTC]
Offset = 0

[Instance0.Window2]
Enabled = false

[Instance0.Keyboard]
HK_SolarSensorIncrease = -1
HK_Mic = -1
X = -1
Up = -1
HK_FrameLimitToggle = -1
HK_SlowMoToggle = -1
HK_FrameStep = -1
Y = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_FastForward = -1
A = -1
HK_SwapScreens = -1
Left = -1
HK_GuitarGripRed = -1
L = -1
R = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_FastForwardToggle = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
HK_SwapScreenEmphasis = -1
HK_PowerButton = -1
HK_Reset = -1
Down = -1
B = -1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_GuitarGripYellow = -1

[Instance0.Joystick]
HK_SolarSensorIncrease = -1
HK_Mic = -1
X = 2
Up = 17891585
HK_FrameLimitToggle = -1
HK_SlowMoToggle = -1
HK_FrameStep = -1
Y = 3
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_FastForward = -1
A = 0
HK_SwapScreens = -1
Left = 1114376
HK_GuitarGripRed = -1
L = 4
R = 5
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_FastForwardToggle = -1
HK_Pause = -1
Right = 65794
Start = 7
Select = 6
HK_SwapScreenEmphasis = -1
HK_PowerButton = -1
HK_Reset = -1
Down = 16843012
B = 1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1
HK_GuitarGripYellow = -1

[Instance0.Firmware]
MAC = ""
Message = ""
BirthdayDay = 1
BirthdayMonth = 1
FavouriteColour = 0
Language = 1
Username = "melonDS"

[Instance0.Window1]
Enabled = false

[Instance0.Window0]
ShowOSD = true
Geometry = "AdnQywADAAAAAAAAAAAAAAAABP8AAAMfAAAAAQAAABwAAAMCAAABtQAAAAAABAAABQAAAAAAAAAAAAAABP8AAAMf"
ScreenLayout = 3
ScreenRotation = 0
ScreenAspectBot = 1
ScreenGap = 0
ScreenSwap = true
ScreenSizing = 2
IntegerScaling = false
ScreenAspectTop = 1
ScreenFilter = false
Enabled = true

[Instance0.Window3]
Enabled = false

[Instance0.Audio]
Volume = 256
DSiVolumeSync = false

[LAN]
DirectMode = false

[MP]
RecvTimeout = 25
AudioMode = 1

[Mouse]
HideSeconds = 5
Hide = false

[Savestate]
RelocSRAM = false

[Emu]
ConsoleType = 0
ExternalBIOSEnable = false
DirectBoot = true

[3D]
Renderer = 1

[3D.Soft]
Threaded = true

[3D.GL]
ScaleFactor = 5
BetterPolygons = false
HiresCoordinates = true

[Screen]
UseGL = true
VSync = true
VSyncInterval = 1

[JIT]
Enable = false
BranchOptimisations = true
LiteralOptimisations = true
FastMemory = true
MaxBlockSize = 32

[DSi]
NANDPath = ""
BIOS7Path = ""
BIOS9Path = ""
FirmwarePath = ""
FullBIOSBoot = false

[DSi.Camera0]
XFlip = false
InputType = 0
ImagePath = ""
DeviceName = ""

[DSi.Camera1]
XFlip = false
InputType = 0
ImagePath = ""
DeviceName = ""

[DSi.DSP]
HLE = true

[DSi.SD]
Enable = false
ImageSize = 0
ImagePath = "dsisd.bin"
ReadOnly = false
FolderSync = false
FolderPath = ""

[DS]
BIOS9Path = ""
BIOS7Path = ""
FirmwarePath = ""

[DLDI]
Enable = false
ImageSize = 0
ImagePath = "dldi.bin"
ReadOnly = false
FolderSync = false
FolderPath = ""

